#!/bin/sh
#SBATCH --partition=standard
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --output=sm-par-fass-backend.log
#SBATCH --job-name=sm-par-fass


echo "STARTING"

vpkg_require anaconda/2024.02:python3

conda activate fass-backend

echo "SOURCING ENV"

#source $PWD/.env

export APIKEY='332b1c2864593c1fa8c92543dcd188fab2816358' 
export NAME="fassdb"
export USER="fassdb"
export PASS="aKDl99utTr5DJ8FxrsgZtbOSHy7YVr"
export HOST="fassdb.pods.icicleai.tapis.io"
export PORT=443


echo "RUNNING"
uv run gunicorn food_access_model.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8090 --timeout=7200
